"""update metric model

Revision ID: 060b157669ce
Revises: 41fd41c920ad
Create Date: 2025-09-13 09:14:50.126167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '060b157669ce'
down_revision: Union[str, Sequence[str], None] = '41fd41c920ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('metrics', sa.Column('id', sa.UUID(), nullable=False))
    op.add_column('metrics', sa.Column('error_message', sa.Text(), nullable=True))
    op.alter_column('metrics', 'is_up',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.create_index('idx_metric_monitor_timestamp', 'metrics', ['monitor_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_metrics_monitor_id'), 'metrics', ['monitor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_metrics_monitor_id'), table_name='metrics')
    op.drop_index('idx_metric_monitor_timestamp', table_name='metrics')
    op.alter_column('metrics', 'is_up',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('metrics', 'error_message')
    op.drop_column('metrics', 'id')
    # ### end Alembic commands ###
