"""update monitor model

Revision ID: 41fd41c920ad
Revises: 
Create Date: 2025-09-13 08:13:58.995292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '41fd41c920ad'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monitors', sa.Column('max_latency_ms', sa.Integer(), nullable=True))
    op.add_column('monitors', sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    op.alter_column('monitors', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('monitors', 'frequency_sec',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('monitors', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('monitors', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index('idx_monitor_active', 'monitors', ['is_active'], unique=False)
    op.create_index(op.f('ix_monitors_user_id'), 'monitors', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_monitors_user_id'), table_name='monitors')
    op.drop_index('idx_monitor_active', table_name='monitors')
    op.alter_column('monitors', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('monitors', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('monitors', 'frequency_sec',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('monitors', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('monitors', 'updated_at')
    op.drop_column('monitors', 'max_latency_ms')
    # ### end Alembic commands ###
