"""add last_checked_at field to monitor model

Revision ID: 47d9e378a07c
Revises: 84abc4bbf083
Create Date: 2025-09-15 07:19:41.281638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47d9e378a07c'
down_revision: Union[str, Sequence[str], None] = '84abc4bbf083'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monitors', sa.Column('last_checked_at', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('monitors', 'last_checked_at')
    # ### end Alembic commands ###
