"""update metric model error field

Revision ID: 84abc4bbf083
Revises: 060b157669ce
Create Date: 2025-09-13 10:37:59.102847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84abc4bbf083'
down_revision: Union[str, Sequence[str], None] = '060b157669ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('metrics', sa.Column('error', sa.Text(), nullable=True))
    op.drop_column('metrics', 'error_message')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('metrics', sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('metrics', 'error')
    # ### end Alembic commands ###
