"""add celery_task_id field to monitor model

Revision ID: b21e780537de
Revises: 47d9e378a07c
Create Date: 2025-09-15 08:26:23.516024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b21e780537de'
down_revision: Union[str, Sequence[str], None] = '47d9e378a07c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monitors', sa.Column('celery_task_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('monitors', 'celery_task_id')
    # ### end Alembic commands ###
